# ============================
# 1) Builder stage
# ============================
FROM gradle:8.4-jdk17 AS builder
WORKDIR /app
COPY . .
RUN gradle build --no-daemon -x test


# ============================
# 2) Runtime stage
# ============================
FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app

# Copy the compiled JAR from the builder
COPY --from=builder /app/build/libs/*0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080
VOLUME /filestorage/images/

ENTRYPOINT ["java", "-Dspring.profiles.active=prod", "-jar", "app.jar"]
