# Example configuration for project type detection
nextjs:
  dockerfile_template: "Dockerfile-nextjs"

react:
  dockerfile_template: "Dockerfile-react"

springboot-maven:
  dockerfile_template: "Dockerfile-springboot-maven"

springboot-gradle:
  dockerfile_template: "Dockerfile-springboot-gradle"

flutter:
  dockerfile_template: "Dockerfile-flutter"
