projectTypes:
  - name: flutter
    files:
      - pubspec.yaml
      - lib/main.dart
  - name: nextjs
    files:
      - package.json
      - next.config.js
  - name: react
    files:
      - package.json
      - src/index.js
  - name: springboot-gradle
    files:
      - build.gradle
      - src/main/java
  - name: springboot-maven
    files:
      - pom.xml
      - src/main/java

