---
- name: Deploy database with Kubernetes
  hosts: kube_servers
  become: yes
  tasks:
    - name: Copy database deployment script to Kubernetes server
      copy:
        src: ../scripts/
        dest: /home/sen/cloudinator/
        mode: '0755'

    - name: Execute the configuration db
      command: >
        bash /home/sen/cloudinator/database.sh
        {{ DB_NAME }} 
        {{ DB_TYPE }} 
        {{ DB_VERSION }} 
        {{ NAMESPACE }} 
        {{ DB_PASSWORD }} 
        {{ DB_USERNAME }} 
        {{ DOMAIN_NAME }} 
        {{ STORAGE_SIZE }}
        {{ PORT }}
    - name: Execute namespace
      command: >
        bash /home/sen/cloudinator/namespace.sh
        {{ DB_NAME }} 
        {{ DB_TYPE }} 
        {{ DB_VERSION }} 
        {{ NAMESPACE }} 
        {{ DB_PASSWORD }} 
        {{ DB_USERNAME }} 
        {{ DOMAIN_NAME }} 
        {{ STORAGE_SIZE }}
        {{ PORT }}
    - name: Execute storage class
      command: >
        bash /home/sen/cloudinator/storage.sh
        {{ DB_NAME }} 
        {{ DB_TYPE }} 
        {{ DB_VERSION }} 
        {{ NAMESPACE }} 
        {{ DB_PASSWORD }} 
        {{ DB_USERNAME }} 
        {{ DOMAIN_NAME }} 
        {{ STORAGE_SIZE }}
        {{ PORT }}  
    - name: Execute statefulset
      command: >
        bash /home/sen/cloudinator/statefulset.sh
        {{ DB_NAME }} 
        {{ DB_TYPE }} 
        {{ DB_VERSION }} 
        {{ NAMESPACE }} 
        {{ DB_PASSWORD }} 
        {{ DB_USERNAME }} 
        {{ DOMAIN_NAME }} 
        {{ STORAGE_SIZE }}
        {{ PORT }}
    - name: Execute service
      command: >
        bash /home/sen/cloudinator/service.sh
        {{ DB_NAME }} 
        {{ DB_TYPE }} 
        {{ DB_VERSION }} 
        {{ NAMESPACE }} 
        {{ DB_PASSWORD }} 
        {{ DB_USERNAME }} 
        {{ DOMAIN_NAME }} 
        {{ STORAGE_SIZE }}
        {{ PORT }}
    - name: Execute ingress
      command: >
        bash /home/sen/cloudinator/ingress.sh
        {{ DB_NAME }} 
        {{ DB_TYPE }} 
        {{ DB_VERSION }} 
        {{ NAMESPACE }} 
        {{ DB_PASSWORD }} 
        {{ DB_USERNAME }} 
        {{ DOMAIN_NAME }} 
        {{ STORAGE_SIZE }}
        {{ PORT }}  