---
- name: Deploy application with HTTPS to Kubernetes
  hosts: kube_servers
  become: yes
  tasks:
    - name: Create required directories
      file:
        path: "/data/{{ NAMESPACE }}/{{ APP_NAME }}"
        state: directory
        mode: '0700'
        owner: '999'
        group: '999'
      
    - name: Copy shell script to Kubernetes server
      copy:
        src: ../scripts/deploy-k8s.sh
        dest: /home/asura/cloudinator/deploy-k8s.sh
        mode: '0755'

    - name: Execute the shell script with dynamic variables
      become_user: asura
      command: >
        bash /home/asura/cloudinator/deploy-k8s.sh 
        {{ APP_NAME }} 
        {{ IMAGE }} 
        {{ NAMESPACE }} 
        {{ FILE_Path }} 
        {{ DOMAIN_NAME }} 
        {{ EMAIL }}
        {{ PORT }}
      args:
        creates: "/data/{{ NAMESPACE }}/{{ APP_NAME }}"  # Idempotency check