---
- name: Deploy application with HTTPS to Kubernetes
  hosts: kube_servers
  become: yes
  tasks:
    - name: Copy shell script to Kubernetes server
      copy:
        src: ../scripts/deploy-k8s.sh
        dest: /root/cloudinator/deploy-k8s.sh
        mode: '0755'

    - name: Execute the shell script with dynamic variables
      command: >
        bash /root/cloudinator/deploy-k8s.sh 
        {{ APP_NAME }} 
        {{ IMAGE }} 
        {{ NAMESPACE }} 
        {{ FILE_Path }} 
        {{ DOMAIN_NAME }} 
        {{ EMAIL }}
        {{ PORT }}

- name: Create Helm chart and update values
  import_playbook: create-helm-chart.yml

