---
- name: set up helm chart for the application
  hosts: kube_servers
  become: yes
  tasks:
    - name: Copy shell set-up helm script to Kubernetes server
      copy:
        src: ../scripts/helm-setup.sh
        dest: /root/cloudinator/helm-setup.sh
        mode: '0755'

    - name: Execute the shell script for set up helm chart
      command: >
        bash /root/cloudinator/helm-setup.sh 
        {{ CHART_NAME }} 
        {{ IMAGE }} 
        {{ TAG }} 
        {{ PORT }} 
        {{ NAMESPACE }} 
        {{ HOST }}