---
- name: Sync ArgoCD with Kubernetes applications and helm charts
  hosts: kube_servers
  become: true
  become_user: sen
  tasks:
    - name: copy the sync helm to git script
      copy:
        src: ../scripts/sync-helm-to-git.sh
        dest: /home/sen/cloudinator/sync-helm-to-git.sh
        mode: '0755'

    - name: Sync helm chart to git
      become: true
      become_user: sen
      command: bash /home/sen/cloudinator/sync-helm-to-git.sh {{ CHART_NAME }} {{ CHART_VERSION }} 
      environment:
        PATH: "/usr/local/bin:/usr/bin:/bin"
