---
- name: Sync ArgoCD with Kubernetes applications and Helm charts
  hosts: kube_servers
  become: true
  tasks:
    - name: Copy the sync Helm to Git script
      copy:
        src: ../scripts/sync-helm-to-git.sh
        dest: /home/asura/cloudinator/sync-helm-to-git.sh
        mode: '0755'
        owner: asura
        group: asura

    - name: Ensure the target directory is writable
      file:
        path: /home/asura/cloudinator
        mode: '0755'
        owner: asura
        group: asura
        state: directory

    - name: Sync Helm chart to Git
      become_user: asura
      command: bash /home/asura/cloudinator/sync-helm-to-git.sh {{ CHART_NAME }} {{ CHART_VERSION }}
      environment:
        PATH: "/usr/local/bin:/usr/bin:/bin"
      register: sync_result
      ignore_errors: yes

    - name: Debug sync result
      debug:
        msg: "{{ sync_result.stdout }}"
